name: ecommerce_app_firebase
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth:
  firebase_core:
  firebase_storage:
  get:
  google_fonts:
  carousel_slider: ^5.1.1
  shared_preferences:
  cloud_firestore:
  provider:
  image_picker:
  image_picker_ios:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/stocks/
    - assets/images/fiction/